apiVersion: v1
kind: Service
metadata:
  name: shopizer-k8s
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: shopizer-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopizer-k8s
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: shopizer-k8s
  template:
    metadata:
      labels:
        app: shopizer-k8s
    spec:
      containers:
        - name: shopizer-k8s
          image: CONTAINER_IMAGE
          resources:
            requests:
              cpu: 500m
          ports:
            - containerPort: 8080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: shopizer-k8s
  namespace: default
spec:
  maxReplicas: 50
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopizer-k8s
  targetCPUUtilizationPercentage: 50
